const dependsLyrics = `you'reallupinmyheadyou'reafunnykindamedsi'msickyourfriendscondescendtomegotmethinkingonanendtometime'stickedsincewhendoidependonyousincewhendoidependonyouiwasastoneunturnedwasn'tipleasantlypetrifiednowyougotmerollingdownwhatdoyousupposeidotonightisweariwon'tputupafightnowyougotmeonthegroundsincewhendoidependonyousincewhendoidependonyoufromwhenyousteppedintomyhousetowhenyousatdownonmycouchyoucheckedoutfromwhenisteppedintoyourhousetowhenisatdownonyourcouchyoucheckedoutbabesincewhendoidependonyousincewhendoidependonyou`;

export { dependsLyrics };
