// const dependsLyrics = `you'reallupinmyheadyou'reafunnykindamedsi'msickyourfriendscondescendtomegotmethinkingonanendtometime'stickedsincewhendoidependonyousincewhendoidependonyouiwasastoneunturnedwasn'tipleasantlypetrifiednowyougotmerollingdownwhatdoyousupposeidotonightisweariwon'tputupafightnowyougotmeonthegroundsincewhendoidependonyousincewhendoidependonyoufromwhenyousteppedintomyhousetowhenyousatdownonmycouchyoucheckedoutfromwhenisteppedintoyourhousetowhenisatdownonyourcouchyoucheckedoutbabesincewhendoidependonyousincewhendoidependonyou`;
const dependsLyrics = "";

export { dependsLyrics };
